Controllers/CustomerController.cs
using _79_Project.Provider;
using _79_Project.ViewModel.Customer;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _79_Project.Controllers
{
    public class CustomerController : Controller
    {
        CustomerProvider cp = new CustomerProvider();

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult List([DataSourceRequest] DataSourceRequest request)
        {
            return Json(cp.GetListCustomer().ToDataSourceResult(request));
        }
        [AcceptVerbs("Post")]
        public ActionResult EditingPopup_Create([DataSourceRequest] DataSourceRequest request, CreateEditViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                cp.Create(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public ActionResult EditingPopup_Update([DataSourceRequest] DataSourceRequest request, CreateEditViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                cp.Edit(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public ActionResult EditingPopup_Destroy([DataSourceRequest] DataSourceRequest request, CreateEditViewModel model)
        {
            if (model != null)
            {
                cp.Destroy(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
    }
}

Controllers/Report2Controller.cs
using _79_Project.Provider;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _79_Project.Controllers
{
    public class Report2Controller : Controller
    {
        ReportProvider rp = new ReportProvider();

        public IActionResult Index()
        {
            return View();
        }
        public ActionResult GetCustomer()
        {
            return Json(rp.GetCustomer());
        }
    }
}

Controllers/ReportController.cs
using _79_Project.Provider;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _79_Project.Controllers
{
    public class ReportController : Controller
    {
        ReportProvider rp = new ReportProvider();
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult List([DataSourceRequest] DataSourceRequest request)
        {
            return Json(rp.GetListSP_Report1().ToDataSourceResult(request));
        }
        public JsonResult List2([DataSourceRequest] DataSourceRequest request, int accountId, DateTime startDate, DateTime endDate)
        {
            return Json(rp.GetListSP_Report2(accountId, startDate, endDate).ToDataSourceResult(request));
        }
    }
}

Controllers/TransactionController.cs
using _79_Project.Provider;
using _79_Project.ViewModel;
using _79_Project.ViewModel.Transaction;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _79_Project.Controllers
{
    public class TransactionController : Controller
    {
        TransactionProvider tp = new TransactionProvider();

        public IActionResult Index()
        {
            return View();
        }
        public JsonResult List([DataSourceRequest] DataSourceRequest request)
        {
            return Json(tp.GetListTransaction().ToDataSourceResult(request));
        }
        
        #region dropdown
        public ActionResult GetDescription()
        {
            return Json(tp.GetDescription());
        }
        public ActionResult GetStatus()
        {
            return Json(tp.GetStatus());
        }
        #endregion

        public ActionResult Edit(string ID)
        {
            CreateEditViewModel model = tp.GetCreateEdit(ID);
            return View("CreateEdit", model);
        }

        public ActionResult Add()
        {
            CreateEditViewModel model = tp.GetCreateEdit(string.Empty);
            return View("CreateEdit", model);
        }

        [HttpPost]
        public AjaxViewModel Save(CreateEditViewModel model)
        {
            var result = tp.Create(model);
            return result;
        }

        [HttpPost]
        public AjaxViewModel Update(CreateEditViewModel model)
        {
            var result = tp.Edit(model);
            return result;
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _79_Project</title>


    <!--<environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://kendo.cdn.telerik.com/2022.2.510/styles/kendo.bootstrap-main.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2022.2.510/js/jquery.min.js"></script>-->
    @* Add the Kendo UI scripts: *@
    <!--<script src="https://kendo.cdn.telerik.com/2022.2.510/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2022.2.510/js/kendo.aspnetmvc.min.js"></script>-->

    @{ var kendoVersion = "2019.1.115";}
    <link href="https://kendo.cdn.telerik.com/@kendoVersion/styles/kendo.common-material.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/@kendoVersion/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/@kendoVersion/styles/kendo.material.min.css" rel="stylesheet" type="text/css" />

    <script src="https://kendo.cdn.telerik.com/@kendoVersion/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/@kendoVersion/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/@kendoVersion/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/@kendoVersion/js/kendo.aspnetmvc.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">_79_Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report2" asp-action="Index">Report2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - _79_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>*@
        @*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>*@
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>